### PR TITLE
feat(ZNTA-1023): add FileTypeInfo

### PR DESCRIPTION
**Pull request by seanf**
- add FileTypeInfo/Name to transfer DocumentType info over JSON
- add FileResource.fileTypeInfoList() REST endpoint
- deprecate FileResource.acceptedFileTypeList()
- allow DocumentType with no default file extensions
- add default extension for XLIFF (.xlf)

See https://github.com/zanata/zanata-client/pull/113 and https://github.com/zanata/zanata-server/pull/1244

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-api/56)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[zanata-common-api/src/main/java/org/zanata/common/DocumentType.java, line 92 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/56#-KN0J8SadjmJv0PF5VEG:-KN0J8SbnGxHbLubrwxW:1026053326) ([raw file](https://github.com/zanata/zanata-api/blob/dd2c56a76fd7888a951f70f946ed6c24bb6f1a5b/zanata-common-api/src/main/java/org/zanata/common/DocumentType.java#L92)):*
> ```Java
> 
>     public static @Nullable DocumentType getByName(@Nullable String name) {
>         if (name == null) {
> ```

Should we check for empty string too?

---

*[zanata-common-api/src/main/java/org/zanata/common/ProjectType.java, line 44 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/56#-KN0K8BLuqH6SXws74qx:-KN0K8BLuqH6SXws74qy:365248198) ([raw file](https://github.com/zanata/zanata-api/blob/dd2c56a76fd7888a951f70f946ed6c24bb6f1a5b/zanata-common-api/src/main/java/org/zanata/common/ProjectType.java#L44)):*
> ```Java
>     public static ProjectType getValueOf(String projectType) throws Exception {
>         // TODO change all values to upper case and use ProjectType.valueOf(projectType)
>         if (projectType != null && !projectType.isEmpty()) {
> ```

Can be simplify by using StringUtils.isBlank

---

*[zanata-common-api/src/main/java/org/zanata/rest/service/FileResource.java, line 85 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/56#-KN0KnSEpB9G5VbpPegL:-KN0KnSEpB9G5VbpPegM:245451047) ([raw file](https://github.com/zanata/zanata-api/blob/dd2c56a76fd7888a951f70f946ed6c24bb6f1a5b/zanata-common-api/src/main/java/org/zanata/rest/service/FileResource.java#L85)):*
> ```Java
>      * approved translation is available, source strings are used.
>      */
>     public static final String FILETYPE_TRANSLATED_APPROVED = "baked";
> ```

Are we still using `baked` and `half-baked`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/56)*

**Comment by seanf** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[zanata-common-api/src/main/java/org/zanata/common/DocumentType.java, line 92 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/56#-KN0J8SadjmJv0PF5VEG:-KN0UG1Qgl7-ZZI4ODkG:2086258369) ([raw file](https://github.com/zanata/zanata-api/blob/dd2c56a76fd7888a951f70f946ed6c24bb6f1a5b/zanata-common-api/src/main/java/org/zanata/common/DocumentType.java#L92)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Should we check for empty string too?
</details>
I guess it wouldn't hurt. Done.

---

*[zanata-common-api/src/main/java/org/zanata/common/ProjectType.java, line 44 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/56#-KN0K8BLuqH6SXws74qx:-KN0T3s7jNjGpplS7hZz:1225384743) ([raw file](https://github.com/zanata/zanata-api/blob/dd2c56a76fd7888a951f70f946ed6c24bb6f1a5b/zanata-common-api/src/main/java/org/zanata/common/ProjectType.java#L44)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Can be simplify by using StringUtils.isBlank
</details>
Modified the check.

---

*[zanata-common-api/src/main/java/org/zanata/rest/service/FileResource.java, line 85 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/56#-KN0KnSEpB9G5VbpPegL:-KN0RIsaNdRh60B6id6O:-1099501971) ([raw file](https://github.com/zanata/zanata-api/blob/dd2c56a76fd7888a951f70f946ed6c24bb6f1a5b/zanata-common-api/src/main/java/org/zanata/rest/service/FileResource.java#L85)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Are we still using `baked` and `half-baked`?
</details>
I suppose so. I haven't changed any of that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/56)*

**Comment by aeng** [comment]
:lgtm:
+Reviewed 
-(Awaiting review) 

---

Reviewed 1 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/56#-:-KN0ea-tqB5OOxucDkTg:-1576167339)*

**Comment by seanf** [comment]
@aeng It turns out that using `StringUtils.isBlank` (or commons-lang generally) is a bad idea for classes which are compiled by GWT, so I've removed all trace of commons-lang and switched to Guava (and banned commons-lang in API).

**Comment by aeng** [comment]
Reviewed 5 of 6 files at r3.
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[zanata-common-api/pom.xml, line 51 \[r3\]](https://reviewable.io:443/reviews/zanata/zanata-api/56#-KNiGD7PEMw9eETEHnnV:-KNiGD7Qzj4aXSa4r4Zz:907539681) ([raw file](https://github.com/zanata/zanata-api/blob/d97306bd13a62d8c0cdd5ec038a0cc302333fdde/zanata-common-api/pom.xml#L51)):*
> ```XML
>             <bannedDependencies>
>               <excludes combine.children="append">
>                 
> ```

So no more commons-lang in common api?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/56)*

**Comment by seanf** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[zanata-common-api/pom.xml, line 51 \[r3\]](https://reviewable.io:443/reviews/zanata/zanata-api/56#-KNiGD7PEMw9eETEHnnV:-KNilFpxCkFnR_Hheyd2:881506742) ([raw file](https://github.com/zanata/zanata-api/blob/d97306bd13a62d8c0cdd5ec038a0cc302333fdde/zanata-common-api/pom.xml#L51)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> So no more commons-lang in common api?
</details>
That's right. Otherwise, we could break GWT compilation without even realising it. 

Ideally, API wouldn't have *any* dependencies, since anyone using Zanata API will have to bring in those dependencies.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/56)*

**Comment by seanf** [comment]
@aeng  Are you happy with the changes? We have a couple of unresolved discussions in Reviewable.

---

Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/56#-:-KODXwPXYGdicsmc1GR7:-947927657)*

**Comment by seanf** [comment]
@aeng Could you please look at the changes?

**Comment by seanf** [comment]
@carlosmunoz Could you please review the last couple of changes? I'm afraid the bits are going to start rotting again.

**Comment by djansen-redhat** [comment]
Reviewed 1 of 1 files at r5.
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/56)*

**Comment by djansen-redhat** [comment]
Reviewed 4 of 7 files at r1, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/56)*

**Comment by djansen-redhat** [comment]
Pushing to a 3.9 server with a 4.0 client results in
> [ERROR] Failed to execute goal org.zanata:zanata-maven-plugin:4.0.0-SNAPSHOT:push (default-cli) on project standalone-pom: Zanata mojo exception: GET http://localhost:8080/rest/file/file_type_info returned a response status of 404 Not Found -> [Help 1]
> ...
> Caused by: com.sun.jersey.api.client.UniformInterfaceException: GET http://localhost:8080/rest/file/file_type_info returned a response status of 404 Not Found

**Comment by seanf** [comment]
@davidmason WORKSFORME, at least with Zanata 4.0 master, when running a ZNTA-1023 client compiled against ZNTA-1023 api. Both for `zanata-cli push` and `zanata-cli push --list-file-types`.

    [INFO] Detected old Zanata Server; using hard-coded file types.

(That's instead of spitting out the 404 error.)

Just to be sure, I'll set up to test with Zanata 3.9 instead of 4.0 master, but I might have to get more details off you.

**Pull request merged**
