### PR TITLE
feat(document): ZNTA-689 Support Qt TS files

### PR DESCRIPTION
**Pull request by djansen-redhat**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-api/35)

### CODE REVIEW

**Comment by carlosmunoz** [comment]
@djansen-redhat Might want to have the JIRA id in there somewhere so that it can be picked up automatically

**Comment by djansen-redhat** [comment]
D'oh!

**Comment by seanf** [comment]
@djansen-redhat is this still a work in progress? It seems to be a dependency for https://github.com/zanata/zanata-server/pull/975

**Comment by djansen-redhat** [comment]
@seanf thanks for the heads up - upgraded

**Comment by djansen-redhat** [comment]
Server master tests pass on this change (tested locally)

**Comment by seanf** [comment]
:+1:

**Comment by seanf** [comment]
- [ ] When merging, please make sure this goes into `master` as well as `integration/master`. We will probably delete `integration/master` afterwards.

**Comment by definite** [comment]
When I built zanata-client master, it shows
Failed tests: 
  FileResourceClientTest.testServerAcceptedType:84 
Expected: iterable over ["dtd", "pot", "txt", "idml", "html", "htm", "odt", "odp", "odg", "ods", "srt", "sbt", "sub", "vtt", "properties", "xml"] in any order
     but: Not matched: "ts"

Tests run: 29, Failures: 1, Errors: 0, Skipped: 0

**Comment by definite** [comment]
I think the zanata-client build failed because following does not include the qt .ts:

https://github.com/zanata/zanata-client/blob/master/zanata-rest-client/src/test/java/org/zanata/rest/client/FileResourceClientTest.java#L84

**Comment by djansen-redhat** [comment]
Rebased on master

**Comment by definite** [comment]
Note that this PR does not support context. The context support will be address in other bug.

**Comment by definite** [comment]
:+1:

**Comment by definite** [comment]
QT ts context support issue:
https://zanata.atlassian.net/browse/ZNTA-1132

**Comment by djansen-redhat** [comment]
Merged in 9c7b9f722bc02088e2232bfcdc3159ae7451b108

**Pull request closed without merging**
