### PR TITLE
ZNTA-1352 Upgrade to Enunciate 2.x

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTA-1352 (also https://zanata.atlassian.net/browse/ZNTA-1328)

Generate docs with `mvn site` or this command:

    $ mvn com.webcohesion.enunciate:enunciate-slim-maven-plugin:docs -pl zanata-common-api

Note: For some reason `enunciate-maven-plugin` omits the description/introduction when generating the docs, but `enunciate-slim-maven-plugin` does the right thing.

~~Currently on hold due to https://github.com/stoicflame/enunciate/issues/117 and https://bugs.openjdk.java.net/browse/JDK-8143213~~ It turns out we weren't hitting that problem, we just needed to keep the .java files out of the main classes directory (and out of zanata-common-api.jar).

Note that the bug fix for JDK-8143213 (aka JDK-8076104) is being back-ported to Java 8, and that is tracked here: https://bugs.openjdk.java.net/browse/JDK-8155198

- [x] Wait for https://github.com/zanata/zanata-server/pull/1283 before merging this

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-api/46)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 20 of 38 files at r1.
Review status: 20 of 38 files reviewed at latest revision, 7 unresolved discussions.

---

*[pom.xml, line 44 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/46#-KQZEqu17BPBox_GVnTm:-KQZEqu2gBlQE4vXuTjG:b-aartfz) ([raw file](https://github.com/zanata/zanata-api/blob/abc0453216425b1049a9306b1325d1158fc98001/pom.xml#L44)):*
> ```XML
>     -->
>     <required.java>1.7</required.java>
>     <required.jvm>1.7</required.jvm>
> ```

Should this be 1.8 now?

---

*[zanata-common-api/pom.xml, line 23 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/46#-KQZFtmEhicJ5RGlzyBQ:-KQZFtmFGbyXWxmMYet4:bmxi4as) ([raw file](https://github.com/zanata/zanata-api/blob/abc0453216425b1049a9306b1325d1158fc98001/zanata-common-api/pom.xml#L23)):*
> ```XML
> 
>   <properties>
>     <enunciate.version>2.3.0</enunciate.version>
> ```

Why this version is different from the api pom.xml? It should reuse from root pom.xml?

<enunciate.version>2.6.0</enunciate.version>

---

*[zanata-common-api/src/main/java/org/zanata/rest/service/AccountResource.java, line 44 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/46#-KQZFKUP2ANflZvrrzmz:-KQZFKUQIm0FMIRJYh6V:bvby53f) ([raw file](https://github.com/zanata/zanata-api/blob/abc0453216425b1049a9306b1325d1158fc98001/zanata-common-api/src/main/java/org/zanata/rest/service/AccountResource.java#L44)):*
> ```Java
>  */
> @Path(AccountResource.SERVICE_PATH)
> //@ExternallyManagedLifecycle
> ```

If not used, should we just delete this line?

---

*[zanata-common-api/src/main/java/org/zanata/rest/service/AsynchronousProcessResource.java, line 51 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/46#-KQZFRl20VgCI_8yfk8F:-KQZFRl20VgCI_8yfk8G:b-uu6m6m) ([raw file](https://github.com/zanata/zanata-api/blob/abc0453216425b1049a9306b1325d1158fc98001/zanata-common-api/src/main/java/org/zanata/rest/service/AsynchronousProcessResource.java#L51)):*
> ```Java
>  */
> @Path(AsynchronousProcessResource.SERVICE_PATH)
> //@ExternallyManagedLifecycle
> ```

If not used, should we just delete it?

---

*[zanata-common-api/src/main/java/org/zanata/rest/service/CopyTransResource.java, line 40 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/46#-KQZFXQZFDF1W-i8Jh94:-KQZFXQ_4M-xT6AJkrib:b-uu6m6m) ([raw file](https://github.com/zanata/zanata-api/blob/abc0453216425b1049a9306b1325d1158fc98001/zanata-common-api/src/main/java/org/zanata/rest/service/CopyTransResource.java#L40)):*
> ```Java
>  */
> @Path(CopyTransResource.SERVICE_PATH)
> //@ExternallyManagedLifecycle
> ```

If not used, should we just delete it?

---

*[zanata-common-api/src/main/java/org/zanata/rest/service/FileResource.java, line 46 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/46#-KQZF_16Uz4Muc2-Zxg2:-KQZF_16Uz4Muc2-Zxg3:b-uu6m6m) ([raw file](https://github.com/zanata/zanata-api/blob/abc0453216425b1049a9306b1325d1158fc98001/zanata-common-api/src/main/java/org/zanata/rest/service/FileResource.java#L46)):*
> ```Java
>  */
> @Path(FileResource.SERVICE_PATH)
> //@ExternallyManagedLifecycle
> ```

If not used, should we just delete it?

---

*[zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java, line 55 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/46#-KQZFajRF-DOLQqT0uxd:-KQZFajRF-DOLQqT0uxe:bwcw4gr) ([raw file](https://github.com/zanata/zanata-api/blob/abc0453216425b1049a9306b1325d1158fc98001/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java#L55)):*
> ```Java
>  **/
> @Path(GlossaryResource.SERVICE_PATH)
> //@ExternallyManagedLifecycle
> ```

If not used, should we just delete it? Need to check for all the commented //@ExternallyManagedLifecycle

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/46)*

**Comment by seanf** [comment]
Review status: 20 of 38 files reviewed at latest revision, 7 unresolved discussions.

---

*[pom.xml, line 44 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/46#-KQZEqu17BPBox_GVnTm:-KQZR2gJU6wv03jgJ_nH:bqdcc8c) ([raw file](https://github.com/zanata/zanata-api/blob/abc0453216425b1049a9306b1325d1158fc98001/pom.xml#L44)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Should this be 1.8 now?
</details>
Not yet. I'd prefer to make that change separately.

---

*[zanata-common-api/pom.xml, line 23 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/46#-KQZFtmEhicJ5RGlzyBQ:-KQZRdFxFtqCLcOvbCgS:b-ihzp56) ([raw file](https://github.com/zanata/zanata-api/blob/abc0453216425b1049a9306b1325d1158fc98001/zanata-common-api/pom.xml#L23)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Why this version is different from the api pom.xml? It should reuse from root pom.xml?
> 
> <enunciate.version>2.6.0</enunciate.version>
</details>
I had intended to move the version number out of the api pom into zanata-common-api, and managed to make a mess of it. Fixed now.

---

*[zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java, line 55 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/46#-KQZFajRF-DOLQqT0uxd:-KQZUYV2JhSVzftKR3Jt:bocnkof) ([raw file](https://github.com/zanata/zanata-api/blob/abc0453216425b1049a9306b1325d1158fc98001/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java#L55)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> If not used, should we just delete it? Need to check for all the commented //@ExternallyManagedLifecycle
</details>
Yep, I'll remove them now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/46)*

**Comment by aeng** [comment]
Reviewed 18 of 18 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/46)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/46#-:-KQbeyWGaH-MZp81tyWD:bnfp4nl)*

**Comment by seanf** [comment]
@djansen-redhat if you get a chance, could you please put this ahead of my other On QA items? I'm making other API changes which would benefit from having these changes ready.

**Pull request merged**
