### PR TITLE
Basic JSON support

### PR DESCRIPTION
**Pull request by djansen-redhat**
Required for https://github.com/zanata/zanata-client/pull/125 and https://github.com/zanata/zanata-server/pull/1261

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-api/58)

### CODE REVIEW

**Comment by seanf** [comment]
@djansen-redhat This has a conflict.

Also, would it break anything if this were merged before https://github.com/zanata/zanata-server/pull/1261 ?

**Comment by seanf** [comment]
@djansen-redhat This looks okay, but the conflict does need to be resolved.

**Comment by seanf** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[zanata-common-api/src/main/java/org/zanata/common/DocumentType.java, line 59 at r1](https://reviewable.io:443/reviews/zanata/zanata-api/58#-KStghHVEZk1TioAgYNa:-KStghHVEZk1TioAgYNb:b-2tk5tv) ([raw file](https://github.com/zanata/zanata-api/blob/e8b2f419ff67aebb4587316e14b28d942783ca71/zanata-common-api/src/main/java/org/zanata/common/DocumentType.java#L59)):*
> ```Java
>     OPEN_DOCUMENT_DATABASE("odb"), OPEN_DOCUMENT_FORMULA("odf"),
> 
>     HTML("html", "htm"), IDML("idml"), JSON("json"),
> ```

Sorry, I know I said it looked fine...

To minimise the impact of modifying an enum, it's probably best to add new values at the end. Otherwise, the ordinal values of the values further down will be changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/58)*

**Comment by djansen-redhat** [comment]
@seanf moved the JSON enum to the end.

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/58#-:-KTHCg6xYMepBG-4YJu5:bnfp4nl)*

**Pull request merged**
