### PR TITLE
feat(glossary): Project glossary support

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1101

common: https://github.com/zanata/zanata-common/pull/30
client: https://github.com/zanata/zanata-client/pull/127
server: https://github.com/zanata/zanata-server/pull/1285

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-api/61)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[zanata-common-api/src/main/java/org/zanata/rest/dto/QualifiedName.java, line 13 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/61#-KQxZGuxSzB0oc3YFl_-:-KQxZGuxSzB0oc3YFl_0:b-ecbp2p) ([raw file](https://github.com/zanata/zanata-api/blob/82c75056740c4b674e203cec324aa24ffc55ae57/zanata-common-api/src/main/java/org/zanata/rest/dto/QualifiedName.java#L13)):*
> ```Java
> import org.zanata.rest.MediaTypes;
> 
> /**
> ```

Need javadoc to explain what is a QualifiedName

---

*[zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java, line 85 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/61#-KQx_-w7tOrB18y2sRns:-KQx_-w895gyCuioX0GE:b-n1bir2) ([raw file](https://github.com/zanata/zanata-api/blob/82c75056740c4b674e203cec324aa24ffc55ae57/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java#L85)):*
> ```Java
>      */
>     @GET
>     @Path("/qualifiedName")
> ```

The path (qualifiedName) doesn't seem to relate to the returned result (all glossary entries in the system) in javadoc. I think you got the javadoc wrong. If it's going to return a list of qualified name. Maybe the path should be plural form?

---

*[zanata-common-api/src/main/java/org/zanata/rest/service/ProjectResource.java, line 120 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-api/61#-KQx_lu3AA2UAABcZOVR:-KQx_lu3AA2UAABcZOVS:b-sbjye8) ([raw file](https://github.com/zanata/zanata-api/blob/82c75056740c4b674e203cec324aa24ffc55ae57/zanata-common-api/src/main/java/org/zanata/rest/service/ProjectResource.java#L120)):*
> ```Java
>      * @return The following response status codes will be returned from this
>      *         operation:<br>
>      *         OK(200) - Response containing all Glossary entries in the system.
> ```

javadoc seems to be wrong?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/61)*

**Comment by huangp** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java, line 89 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-api/61#-KR142BTuuljgjkZgXCN:-KR142BTuuljgjkZgXCO:b-fi9d8e) ([raw file](https://github.com/zanata/zanata-api/blob/acf12db5aea4b7f3a4573a2c9c8c1990467d20e8/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java#L89)):*
> ```Java
>     @Produces({ MediaTypes.APPLICATION_ZANATA_GLOSSARY_JSON,
>         MediaType.APPLICATION_JSON })
>     @TypeHint(List.class)
> ```

If this endpoint only return global qualified name, why the type hint is List?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/61)*

**Comment by aeng** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java, line 89 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-api/61#-KR142BTuuljgjkZgXCN:-KR15PaM9GMs0AnzbQTZ:bqbwr1h) ([raw file](https://github.com/zanata/zanata-api/blob/acf12db5aea4b7f3a4573a2c9c8c1990467d20e8/zanata-common-api/src/main/java/org/zanata/rest/service/GlossaryResource.java#L89)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> If this endpoint only return global qualified name, why the type hint is List?
</details>
Its for if we got more than 1 global glossary set in the future. At the moment its only 1 global. I've updated the javadoc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/61)*

**Comment by huangp** [comment]
:lgtm: I'd prefer the global endpoint to be in plural form if it's returning a list. e.g. /qualifiedNames but not a blocker.  -(Awaiting review)  +(ON QA) 

---

Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/61#-:-KR16iqKVFMyKx0ZgzLI:bei9xmp)*

**Pull request merged**
