### PR TITLE
fix(glossary): update return type to only json

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-895

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-api/51)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
:+1: ready to test

**Comment by djansen-redhat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-api/51)*

**Comment by djansen-redhat** [comment]
@aeng Will this automatically change the docs on Cloudbees?

**Comment by aeng** [comment]
@djansen-redhat yes. Docs in cloudbees is generated from comments from api.

**Comment by djansen-redhat** [comment]
:white_check_mark: tested

**Pull request merged**
